### ISSUE TITLE
Simplify PLL coefficients handling

### ISSUE THREAD

**Issue by StefanoSperetta** [FlaReSS/gr-flaress#5]
Currently, the PLL receives a single array containing the loop finger coefficients for both 2nd and 3rd order filters. It would be more modular to pass an array describing a single loop filter (so that the PLL does not need to implement a selection between loop filters) and select the loop filter from the outside (with multiple loop filter generators).

**Comment by AMiragliaISISpace** [comment]
I updated the internal structure of the PLL. I also made some quick tests, but all the qa_tests need to be updated with the new format
